//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class AlertRule
    {
        public int AlertRuleID { get; set; }
        public string RuleName { get; set; }
        public string AltertInfo { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> AheadOfTime { get; set; }
        public string Rules { get; set; }
    }
    
}
