//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class ForecastPermeableRate
    {
        public int ForecastPermeableRateID { get; set; }
        public Nullable<int> MBRID { get; set; }
        public string FormulaBefore { get; set; }
        public string FormulaAfter { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual MBRMembrane MBRMembrane { get; set; }
    }
    
}
