//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class Param
    {
        public string ParamID { get; set; }
        public string Title { get; set; }
        public string Unit { get; set; }
        public string Format { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> IsCurve { get; set; }
        public string RreshInterval { get; set; }
        public Nullable<double> ScaleYMax { get; set; }
        public Nullable<double> ScaleYMin { get; set; }
        public Nullable<double> ParamMax { get; set; }
        public Nullable<double> ParamMin { get; set; }
        public string Remark { get; set; }
    }
    
}
