//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class PermeableRrateAlert
    {
        public int PermeableRrateAlertID { get; set; }
        public Nullable<double> OnlineMin { get; set; }
        public Nullable<double> OnlineMax { get; set; }
        public Nullable<double> OfflineMin { get; set; }
        public Nullable<double> OfflineMax { get; set; }
        public Nullable<double> ChangeMin { get; set; }
        public Nullable<double> ChangeMax { get; set; }
        public Nullable<double> DurationMax { get; set; }
    }
    
}
