//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class RunRecord
    {
        public int RunRecordID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public Nullable<double> Column_4 { get; set; }
        public Nullable<double> Column_5 { get; set; }
        public Nullable<double> Column_6 { get; set; }
        public Nullable<double> Column_7 { get; set; }
        public Nullable<double> Column_8 { get; set; }
        public Nullable<double> Column_9 { get; set; }
        public Nullable<double> Column_10 { get; set; }
        public Nullable<double> Column_11 { get; set; }
        public Nullable<double> Column_12 { get; set; }
        public Nullable<double> Column_13 { get; set; }
        public Nullable<double> Column_14 { get; set; }
        public Nullable<double> Column_15 { get; set; }
        public Nullable<double> Column_16 { get; set; }
        public Nullable<double> Column_17 { get; set; }
        public Nullable<double> Column_18 { get; set; }
        public Nullable<double> Column_19 { get; set; }
        public Nullable<double> Column_20 { get; set; }
    
        public virtual Line Line { get; set; }
    }
    
}
